log4r_config:
  preconfig:
    global:
      level: DEBUG
    root:
      level: DEBUG

  loggers:
    - name: bitcoind
      level: DEBUG
      additive: 'false'
      trace: 'false'
      outputters:
        - stdout
        - logfile
        - chainsaw

    - name: deals
      level: DEBUG
      additive: 'false'
      trace: 'false'
      outputters:
        - stdout
        - logfile
        - chainsaw

    - name: reserve_line_items
      level: DEBUG
      additive: 'false'
      trace: 'false'
      outputters:
        - stdout
        - logfile
        - chainsaw

  # outputters and formatters
  outputters:
  - type: StderrOutputter
    name: stderr
    level: WARN
    formatter:
      date_pattern: '%y%m%d %H:%M:%S'
      pattern: '%d [%c] %l: %m'
      type: PatternFormatter
 
  - type: DateFileOutputter
    name: logfile
    level: DEBUG
    date_pattern: '%Y%m%d'
    trunc: 'false'
    dirname: "#{HOME}/log"
    formatter:
      date_pattern: '%y%m%d %H:%M:%S'
      pattern: '%d [%c] %l: %m'
      type: PatternFormatter
 
  - type: UDPOutputter
    name: chainsaw
    level: DEBUG
    hostname: 127.0.0.1
    port: "8071"
    formatter:
      type: Log4jXmlFormatter